import { Project } from "@/types";

export const projects: Project[] = [
      {
        title: 'Recommandation de musique',
        handle: 'SAE 5-6',
        type: 'Universitaire',
        resume: 'Projet en cours ! Création d\'un site de recommandation de musiques.',
        description: 'Projet en cours ! Création d\'un site de recommandation de musiques. Équipe de 8 étudiants. Recueil de données, analyses IA sur des habitudes musicales, création de base, création de systèmes de recommandation, API, site et sécurisation du site.',
        technologies: ['Python', 'Pandas & Matplotlib & Numpy', 'Postegre SQL', 'JS', 'HTML/CSS', 'PHP'],
        githubLink: 'https://github.com/IUT-InTheEnd/analyse',
        demoLink: '',
        image: '/projects/recomusique.png',
        images: [
          '/projects/sae5/1.png',
          '/projects/sae5/2.png',
          '/projects/sae5/3.png',
        ],
        link: 'site-recomusique'
      },
      {
        title: 'Plateforme de tourisme',
        handle: 'SAE 3-4',
        type: 'Universitaire',
        resume: 'Site web dynamique et responsif d\'avis et de conseils touristiques en Côtes d\'armor.',
        description: 'L\'objectif final est de réaliser un site web dynamique et responsif d\'avis et de conseils touristiques en Côtes d\'armor. Le projet a été réalisé en équipe de 7 étudiants et géré en Agile Scrum.\nVoici plusieurs fonctionnalités réalisées : Création d\'une API, création d\'un framework personnalisé, authentification, facturation, notifications, carte et filtres, messagerie',
        technologies: ['PHP', 'Tailwind CSS', 'JS', 'PostegreSQL'],
        githubLink: 'https://github.com/stephantoine/A7-PACT',
        demoLink: '',
        image: '/projects/pact1.png',
        images: [
          '/projects/sae3/pact1.png',
          '/projects/sae3/pact2.png',
          '/projects/sae3/pact3.png',
          '/projects/sae3/pact4.png',
          '/projects/sae3/pact5.png',
          '/projects/sae3/pact6.png',
          '/projects/sae3/pact8.png',
          '/projects/sae3/pact9.png',
          '/projects/sae3/pact10.png',
          '/projects/sae3/pact11.png',
          '/projects/sae3/pact12.png'
        ],
        link: 'site-pact'
      },
      {
        title: 'Site de cuisine',
        handle: 'Site de cuisine',
        type: 'Personnel',
        resume: 'Projet en cours ! Site de cuisine pour recenser les recettes de ma mère.',
        description: 'Projet en cours ! Site de cuisine responsif pour recenser les recettes de ma mère. Recueil de ses besoins, maquettage, développement et production.',
        technologies: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Postegre SQL', 'Supabase'],
        githubLink: 'https://github.com/stephantoine/site-cuisine',
        demoLink: '',
        image: '/projects/site_cuisine.png',
        images: [
          '/projects/site_cuisine/1.png',
          '/projects/site_cuisine/2.png',
          '/projects/site_cuisine/3.png'
        ],
        link: 'cuisine'
      },
      {
        title: 'Outil d\'analyse décisionnelle',
        handle: 'Analyse decisionnelle',
        type: 'Universitaire',
        resume: 'Outil d\'analyse décisionnelle sur l\'équité entre les différentes disciplines des jeux olympiques.',
        description: 'Outil d\'analyse décisionnelle sur l\'équité entre les différentes disciplines des jeux olympiques.',
        technologies: ['Python', 'Streamlit', 'Pandas & Matplotlib & Numpy'],
        githubLink: 'https://github.com/stephantoine/R5C.06_analyse_decisionnelle',
        demoLink: '',
        image: '/projects/decision.png',
        images: ['/projects/decision.png'],
        link:'analyse-decisionnelle'
      },
      {
        title: 'Site portfolio',
        handle: 'portfolio',
        type: 'Personnel',
        resume: 'Site portfolio pour exposer mes projets et les compétences développées.',
        description: 'Site portfolio (celui sur lequel vous vous trouvez actuellement), pour exposer les différentes compétences développées lors de mon BUT informatique, ainsi que les différents projets que j\'ai pu réaliser. Premier site réalisé avec Next.JS',
        technologies: ['Next JS', 'React', 'Tailwind', 'TypeScript'],
        githubLink: 'https://github.com/stephantoine/portfolio',
        demoLink: '',
        image: '/projects/portfolio.png',
        images: ['/projects/portfolio.png'],
        link: 'portfolio'
      },
      {
        title: 'Site intranet gendarmerie',
        handle: 'Site gendarmerie',
        type: 'Professionnel',
        resume : 'Site intranet d\'accueil pour le groupement de gendarmerie des Côtes d\'Armor.', 
        description: 'Dans le cadre d\'un stage j\'ai réalisé un site intranet d\'accueil pour la gendarmerie. En autonomie, j\'ai développé la page principale et des modules de communciation et de réservation de matériel. Par la suite j\ai rédigé des documentations utilisateur et technique.  ',
        technologies: ['Drupal', 'PHP', 'Boostrap 4', 'HTML', 'JS'],
        githubLink: '',
        demoLink: '',
        image: '/projects/ggd.png',
        images: ['/projects/ggd.png'],
        link: 'site-gendarmerie'
      },
      {
        title: 'Site de recherche sur les pays',
        handle: 'Projet JS',
        type: 'Universitaire',
        resume: 'Site de recherche sur des données de pays.',
        description: 'Site de recherche sur les données des pays. Filtrage, recherche et tri sur les données, avec pagination. Manipulation de json avec JavaScript et création de classes pour manipuler les données.',
        technologies: ['JS', 'HTML / CSS'],
        githubLink: 'https://github.com/stephantoine/JS-project',
        demoLink: '',
        image: '/projects/pays.png',
        images: ['/projects/pays.png'],
        link: 'site-pays'
      },
      {
        title: 'Base sur les collèges',
        handle: 'SAE 2.04',
        type: 'Universitaire',
        resume: 'Création d\'une base sur les collèges de France.',
        description: 'Création d\'une base sur les collèges de France. Projet réalisé en binôme. Nettoyage des données et peuplement de cette base. Analyse statistique des données par la suite',
        technologies: ['Postegre SQL', 'Python'],
        githubLink: 'https://github.com/stephantoine/S2.04-base',
        demoLink: '',
        image: '/projects/base.png',
        images: ['/projects/base.png'],
        link: 'site-base'
      },
      {
        title: 'Application de gestion',
        handle: 'SAE 2.01',
        type: 'Universitaire',
        resume: 'Application de gestion des réservation de spectacle.',
        description: 'Application pour modifier les réservation d\'un spectacle et visualiser en direct les places réservées. Équipe de 3 étudiants avec gestion de projet en Gantt. Création de la maquette avec JavaFx et partie fonctionnelle en java en suivant un modèle MVC',
        technologies: ['Java', 'JavaFx'],
        githubLink: 'https://github.com/stephantoine/appli-spectacle',
        demoLink: '',
        image: '/projects/spectacle.png',
        images: ['/projects/spectacle.png'],
        link: 'site-spectacle'
      },
      // {
      //   title: 'Site de gestion de tâches',
      //   handle: 'Site de tâches',
      //   type: 'Personnel',
      //   description: 'A recipe search application using the Edamam API.',
      //   technologies: ['React', 'Edamam API'],
      //   githubLink: 'https://github.com/stephantoine/tasks',
      //   demoLink: '',
      //   image: '/projects/recipe-finder.png',
      // },
      {
        title: 'Ancien site portfolio',
        handle: 'Ancien portfolio',
        type: 'Personnel',
        resume: 'Ancien site porfolio simple en vanilla.',
        description: 'Site portfolio simple en vanilla pour exposer mes projets et me présenter.',
        technologies: ['HTML', 'CSS', 'JS'],
        githubLink: '',
        demoLink: '',
        image: '/projects/ancien_portfolio.png',
        images: ['/projects/ancien_portfolio.png'],
        link: 'ancien-site-portfolio'
      },
      {
        title: 'Génération automatique de documentations',
        handle: 'SAE 1.03',
        type: 'Universitaire',
        resume: 'Algorithme de génération automatique de documentation.',
        description: 'Réalisation d\'un algorithme de génération automatique de documentation pdf stylisées en HTML / CSS à partir de codes sources en C dans un environnement dockerisé',
        technologies: ['HTML', 'CSS', 'Bash', 'PHP', 'Docker'],
        githubLink: 'https://github.com/stephantoine/gen-doc',
        demoLink: '',
        image: '/projects/s1.03.png',
        images: ['/projects/s1.03.png'],
        link: 'site-gen-doc'
      },
      {
        title: 'Organisation d\'un évènement de team-building',
        handle: 'SAE 2.06',
        type: 'Universitaire',
        resume: 'Simulation d\'un évènement de team-building.',
        description: 'Simulation d\'un évènement de team-building pour une entreprise, création de flyer, de film événementiel pour la com de l\'entreprise.',
        technologies: ['Canva', 'DaVinci Resolve'],
        githubLink: '',
        demoLink: '',
        image: '/projects/film.png',
        images: ['/projects/film.png'],
        link: 'site-film'
      },
      {
        title: 'Algorithmes de résolution de sudoku',
        handle: 'SAE 1.02',
        type: 'Universitaire',
        resume: 'Réalisation d\'un jeu de sudoku et d\'algorithmes de résolution.',
        description: 'Création d\'un jeu de sudoku dans le terminal, puis comparaison de différents algorithmes de résolution du sudoku, avec des difficultés de plus en plus élevés.',
        technologies: ['C', 'Doxygen'],
        githubLink: 'https://github.com/stephantoine/S2.02-cavalier',
        demoLink: '',
        image: '/projects/reso_sudoku.png',
        images: ['/projects/reso_sudoku.png'],
        link: 'site-sudoku'
      }
      
  ];