import { Project } from "@/types";

export const projects: Project[] = [
      {
        title: 'Recommandation de musique',
        handle: 'SAE 5-6',
        type: 'Universitaire',
        description: 'Projet en cours ! Site avec système de recommandation de musique. Équipe de 8 étudiants. Recueil de données, analyses IA sur des habitudes musicales, création de base pour de la Big Data, système de recommandation.',
        technologies: ['Python', 'Panda & Matplotlib', 'Postegre SQL'],
        githubLink: 'https://github.com/IUT-InTheEnd/analyse',
        demoLink: '',
        image: '/projects/recomusique.png',
      },
      {
        title: 'Plateforme de tourisme',
        handle: 'SAE 3-4',
        type: 'Universitaire',
        description: 'Site web dynamique et responsif d\'avis et de conseils touristiques en Côtes d\'armor. Équipe de 7 étudiant gérée en Agile Scrum. Réalisation d\'une API et création d\'un framework personnalisé. Authentification, facturation, notifications, carte et filtres, messagerie.',
        technologies: ['PHP', 'Tailwind CSS', 'JS', 'PostegreSQL'],
        githubLink: 'https://github.com/stephantoine/A7-PACT',
        demoLink: '',
        image: '/projects/pact1.png'
      },
      {
        title: 'Site de cuisine',
        handle: 'Site de cuisine',
        type: 'Personnel',
        description: 'Projet en cours ! Site de cuisine responsif pour les recenser les recettes de ma mère. Recueil de ses besoins, maquettage, développement et production.',
        technologies: ['React', 'Next.js', 'TypeScript', 'Tailwind CSS', 'Postegre SQL', 'Supabase'],
        githubLink: 'https://github.com/stephantoine/site-cuisine',
        demoLink: '',
        image: '/projects/site_cuisine.png',
      },
      {
        title: 'Site portfolio',
        handle: 'portfolio',
        type: 'Personnel',
        description: 'Site portfolio (celui sur lequel vous vous trouvez actuellement), pour exposer les différentes compétences développées lors de mon BUT informatique, ainsi que les différents projets que j\'ai pu réaliser. Premier site réalisé avec Next.JS',
        technologies: ['Next JS', 'React', 'Tailwind', 'TypeScript'],
        githubLink: 'https://github.com/stephantoine/portfolio',
        demoLink: '',
        image: '/projects/portfolio.png',
      },
      {
        title: 'Site intranet gendarmerie',
        handle: 'Site gendarmerie',
        type: 'Professionnel',
        description: 'Dans le cadre d\'un stage j\'ai réalisé un site intranet d\'accueil pour la gendarmerie. En autonomie, j\'ai développé la page principale et des modules de communciation et de réservation de matériel. Par la suite j\ai rédigé des documentations utilisateur et technique.  ',
        technologies: ['Drupal', 'PHP', 'Boostrap 4', 'HTML', 'JS'],
        githubLink: '',
        demoLink: '',
        image: '/projects/ggd.png',
      },
      {
        title: 'Site de recherche sur les pays',
        handle: 'Projet JS',
        type: 'Universitaire',
        description: 'Site de recherche sur les données des pays. Filtrage, recherche et tri sur les données, avec pagination. Manipulation de json avec JavaScript et création de classes pour manipuler les données.',
        technologies: ['JS', 'HTML / CSS'],
        githubLink: 'https://github.com/stephantoine/JS-project',
        demoLink: '',
        image: '/projects/pays.png',
      },
      {
        title: 'Base sur les collèges',
        handle: 'SAE 2.04',
        type: 'Universitaire',
        description: 'Création d\'une base sur les collèges de France. Projet réalisé en binôme. Nettoyage des données et peuplement de cette base. Analyse statistique des données par la suite',
        technologies: ['Postegre SQL', 'Python'],
        githubLink: 'https://github.com/stephantoine/S2.04-base',
        demoLink: '',
        image: '/projects/base.png',
      },
      {
        title: 'Application de gestion',
        handle: 'SAE 2.01',
        type: 'Universitaire',
        description: 'Application pour modifier les réservation d\'un spectacle et visualiser en direct les places réservées. Équipe de 3 étudiants avec gestion de projet en Gantt. Création de la maquette avec JavaFx et partie fonctionnelle en java en suivant un modèle MVC',
        technologies: ['Java', 'JavaFx'],
        githubLink: 'https://github.com/stephantoine/appli-spectacle',
        demoLink: '',
        image: '/projects/spectacle.png',
      },
      // {
      //   title: 'Site de gestion de tâches',
      //   handle: 'Site de tâches',
      //   type: 'Personnel',
      //   description: 'A recipe search application using the Edamam API.',
      //   technologies: ['React', 'Edamam API'],
      //   githubLink: 'https://github.com/stephantoine/tasks',
      //   demoLink: '',
      //   image: '/projects/recipe-finder.png',
      // },
      {
        title: 'Ancien site portfolio',
        handle: 'Ancien portfolio',
        type: 'Personnel',
        description: 'Site portfolio simple en vanilla pour exposer mes projets et me présenter.',
        technologies: ['HTML', 'CSS', 'JS'],
        githubLink: '',
        demoLink: '',
        image: '/projects/ancien_portfolio.png',
      },
      {
        title: 'Génération automatique de documentations',
        handle: 'SAE 1.03',
        type: 'Universitaire',
        description: 'Réalisation d\'un algorithme de génération automatique de documentation pdf stylisées en HTML / CSS à partir de codes sources en C dans un environnement dockerisé',
        technologies: ['HTML', 'CSS', 'Bash', 'PHP', 'Docker'],
        githubLink: 'https://github.com/stephantoine/gen-doc',
        demoLink: '',
        image: '/projects/s1.03.png',
      },
      {
        title: 'Organisation d\'un évènement de team-building',
        handle: 'SAE 2.06',
        type: 'Universitaire',
        description: 'Simulation d\'un évènement de team-building pour une entreprise, création de flyer, de film événementiel pour la com de l\'entreprise.',
        technologies: ['Canva', 'DaVinci Resolve'],
        githubLink: '',
        demoLink: '',
        image: '/projects/film.png',
      },
      {
        title: 'Algorithmes de résolution de sudoku',
        handle: 'SAE 1.02',
        type: 'Universitaire',
        description: 'Création d\'un jeu de sudoku dans le terminal, puis comparaison de différents algorithmes de résolution du sudoku, avec des difficultés de plus en plus élevés.',
        technologies: ['C'],
        githubLink: 'https://github.com/stephantoine/S2.02-cavalier',
        demoLink: '',
        image: '/projects/reso_sudoku.png',
      }
      
  ];